name: Deploy to AWS Lambda

on:
  release:
    types:
      - published

permissions:
  id-token: write # This is required for OIDC authentication
  contents: read # This is required to checkout the repository

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          # The role-to-assume should be the ARN of the IAM role you created for GitHub Actions OIDC

      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1.1.0
        with:
          function-name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
          code-artifacts-dir: bin
          handler: bootstrap
          runtime: provided.al2023
          # Add any additional inputs this actionn
